### ISSUE TITLE
`at` cannot be used with a nullable Decoder

### ISSUE THREAD

**Issue by arnauorriols** [kofno/jsonous#6]
As it is currently implemented, `at` is not compatible with a `nullable` decoder:

```typescript
at(["foo", "bar", "fuzz"], nullable(number)).decodeAny({foo: {bar: {fuzz: null}}})
// Err
```

This is because `at` checks if a field is present with `value == null`:
```typescript
export const at = <A>(path: Array<number | string>, decoder: Decoder<A>): Decoder<A> =>
  new Decoder<A>(value => {
    let val = value;
    let idx = 0;
    while (idx < path.length) {
      val = val[path[idx]];
      if (val == null) {  // <== HERE!
        const pathStr = JSON.stringify(path.slice(0, idx + 1));
        const valueStr = JSON.stringify(value);
        return err(`Path failure: Expected to find path '${pathStr}' in ${valueStr}`);
      }
      idx += 1;
    }
    return decoder.decodeAny(val);
  });
```

I'm not an expert in terms of compatibility, so I'm not sure if this could be fixed just replacing this check with `value === undefined`? at least in node: `({})["foo"] === undefined`. 

Note: As a workaround, I'm using `field` to decode the last element of the path:
```typescript
at(["foo", "bar"], field("fuzz", nullable(number))).decodeAny({foo: {bar: {fuzz: null}}})
```

**Comment by kofno** [comment]
Well, we don't want to catch just undefined though. We want it to work for null and undefined

**Comment by kofno** [comment]
oh, wait, I see the PR now. OK...
