### ISSUE TITLE
Is decoding a `dict` supported?

### ISSUE THREAD

**Issue by rmacklin** [kofno/jsonous#8]
Does this support decoding a `dict` as in https://package.elm-lang.org/packages/elm-lang/core/latest/Json-Decode#dict ? If so, what is it called (I don't see `dict` anywhere in this library)?

**Comment by kofno** [comment]
We don't ship a decoder for generically parsing an object into a Map or a key value pairs like that. One could be added, it just hasn't come up as a need in my usage yet.

**Comment by rmacklin** [comment]
I see, thanks. Are there other types that are supported by Elm's decoder that are also not (yet) implemented in `jsonous`? Would you be open to including that information in the `README`?

Additionally, I may look into adding support for `dict` if you are open to external contributors, but this is out of my area of expertise, so I don't want to promise that I could have this done quickly. If you have any pointers/tips/guides that would be helpful for a first time contributor, let me know. Thanks!

**Comment by kofno** [comment]
Resolved by https://github.com/kofno/jsonous/commit/c6a9b10918f6ecf09e4691df31e1b884bbee7c3c
