### ISSUE TITLE
Possible to enforce string union type?

### ISSUE THREAD

**Issue by greim** [kofno/jsonous#9]
If a field should be a union of `'FOO' | 'BAR'` is there a way to enforce that?

**Comment by kofno** [comment]
Sure is. I do it quite a lot. 

I wrote a `stringLiteral` decoder that hasn't made it back into Jsonous yet,, but here's an example of how it would work:

```typescript
import Decoder, { oneOf } from 'jsonous';
import { err, ok } from 'resulty';

type FooBar = 'FOO' | 'BAR';

export const stringLiteral = <T extends string>(t: T): Decoder<T> =>
  new Decoder<T>(v => {
    return t === v ? ok(v) : err(`Expected ${t} but got ${v}`);
  });

export const foobarDecoder = oneOf<FooBar>([
  stringLiteral('FOO'), 
  stringLiteral('BAR')
]);
```

This compiles on Typescript 3.4.5

**Comment by kofno** [comment]
I'm assuming this answered your question.
